In [3]:
import gdown

# Replace the 'file_id' with the actual file ID from the Google Drive shareable link
file_id = '1ZTQJu6kzHSj2BE1tIjPGN23dlUZ6i9Zp'
url = f'https://drive.google.com/uc?id={file_id}'

# Replace 'output' with the desired output file name
output = 'data/swissprot/data-1.zip'

gdown.download(url, output, quiet=False)

# extract the data
import zipfile
with zipfile.ZipFile(output, 'r') as zip_ref:
    zip_ref.extractall('data/swissprot/')
    


Downloading...
From (uriginal): https://drive.google.com/uc?id=1ZTQJu6kzHSj2BE1tIjPGN23dlUZ6i9Zp
From (redirected): https://drive.google.com/uc?id=1ZTQJu6kzHSj2BE1tIjPGN23dlUZ6i9Zp&confirm=t&uuid=f8d7e1d9-69b9-4a2c-903c-a201e03fe171
To: /home/hichemhadhri/DL-Biomed-Relational/data/swissprot/data-1.zip


100%|██████████| 5.58G/5.58G [00:26<00:00, 210MB/s]


'data/swissprot/data-1.zip'

In [5]:
import gdown

# Replace the 'file_id' with the actual file ID from the Google Drive shareable link
file_id = '1a3IFmUMUXBH8trx_VWKZEGteRiotOkZS'
url = f'https://drive.google.com/uc?id={file_id}'

# Replace 'output' with the desired output file name
output = 'data/swissprot/data-2.zip'

gdown.download(url, output, quiet=False)

# extract the data
import zipfile
with zipfile.ZipFile(output, 'r') as zip_ref:
    zip_ref.extractall('./')


Downloading...
From (uriginal): https://drive.google.com/uc?id=1a3IFmUMUXBH8trx_VWKZEGteRiotOkZS
From (redirected): https://drive.google.com/uc?id=1a3IFmUMUXBH8trx_VWKZEGteRiotOkZS&confirm=t&uuid=189b7901-a897-4d8f-abe7-f229250a74a5
To: /home/hichemhadhri/DL-Biomed-Relational/data/swissprot/data-2.zip
100%|██████████| 180M/180M [00:03<00:00, 54.5MB/s]


In [6]:


# Replace the 'file_id' with the actual file ID from the Google Drive shareable link
file_id = '1vRR5EeeE0JfgdFYNoput1yR2H6wNWAG2'
url = f'https://drive.google.com/uc?id={file_id}'

# Replace 'output' with the desired output file name
output = 'data/swissprot/data-3.zip'

gdown.download(url, output, quiet=False)

# extract the data
import zipfile
with zipfile.ZipFile(output, 'r') as zip_ref:
    zip_ref.extractall('data/swissprot/')

Downloading...
From (uriginal): https://drive.google.com/uc?id=1vRR5EeeE0JfgdFYNoput1yR2H6wNWAG2
From (redirected): https://drive.google.com/uc?id=1vRR5EeeE0JfgdFYNoput1yR2H6wNWAG2&confirm=t&uuid=d181198d-6638-497f-8deb-5d005fcbfda0
To: /home/hichemhadhri/DL-Biomed-Relational/data/swissprot/data-3.zip
100%|██████████| 161M/161M [00:03<00:00, 41.7MB/s]


In [46]:
import torch
import torch.nn as nn
import numpy as np



z_protos = torch.randint(0,10,(2,4))
z_queries = torch.randint(0,10,(6,4))
print(z_protos)
print(z_queries)


# repeat z_protos 5 times   
z_queries = z_queries.repeat_interleave(2,0)

z_protos = z_protos.repeat(6,1)

# concat z_protos and z_queries
z_protos = torch.cat((z_protos,z_queries),1)

print(z_protos)


scores = torch.rand(12,1)
print(scores)

scores = scores.view(-1,2)
print(scores.shape)




tensor([[4, 7, 7, 3],
        [4, 7, 7, 3]])
tensor([[6, 6, 9, 3],
        [5, 9, 2, 6],
        [4, 0, 6, 1],
        [4, 9, 3, 4],
        [8, 9, 8, 5],
        [3, 8, 6, 9]])
tensor([[4, 7, 7, 3, 6, 6, 9, 3],
        [4, 7, 7, 3, 6, 6, 9, 3],
        [4, 7, 7, 3, 5, 9, 2, 6],
        [4, 7, 7, 3, 5, 9, 2, 6],
        [4, 7, 7, 3, 4, 0, 6, 1],
        [4, 7, 7, 3, 4, 0, 6, 1],
        [4, 7, 7, 3, 4, 9, 3, 4],
        [4, 7, 7, 3, 4, 9, 3, 4],
        [4, 7, 7, 3, 8, 9, 8, 5],
        [4, 7, 7, 3, 8, 9, 8, 5],
        [4, 7, 7, 3, 3, 8, 6, 9],
        [4, 7, 7, 3, 3, 8, 6, 9]])
tensor([[0.1187],
        [0.9621],
        [0.4910],
        [0.3155],
        [0.3117],
        [0.9652],
        [0.2857],
        [0.8461],
        [0.1668],
        [0.9221],
        [0.8401],
        [0.7171]])
torch.Size([6, 2])


In [47]:
torch.from_numpy(np.repeat(range( 5), 15 )).shape

torch.Size([75])

In [21]:
def euclidean_dist( x, y):
    # x: N x D
    # y: M x D
    n = x.size(0)
    m = y.size(0)
    d = x.size(1)
    assert d == y.size(1)

    x = x.unsqueeze(1).expand(n, m, d)
    y = y.unsqueeze(0).expand(n, m, d)

    return torch.pow(x - y, 2).sum(2)


euclidean_dist(z_queries, z_protos).shape

torch.Size([50, 5])